"""
Django settings for mboapi_djangodemo project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""
import os
import socket
import dj_database_url

BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DEBUG = True

# the SECRETS.py file doesnt exist.  Create it and fill in the declarations
from .SECRETS import *

EMAIL_HOST = MAIL_SERVER
EMAIL_HOST_USER = MAIL_SERVER_USER
EMAIL_HOST_PASSWORD = MAIL_SERVER_PASS
EMAIL_PORT = 587
EMAIL_USE_TLS = True


SECRET_KEY = APPLICATION_SECRET


INSTALLED_APPS = (
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django.forms',
    'crispy_forms',
    'web',
    'helpers',
    'django.core.mail'
)

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

SESSION_SAVE_EVERY_REQUEST = True

ROOT_URLCONF = 'mboapi_djangodemo.urls'

PROJECT_DIR = os.path.dirname(__file__)

TEMPLATE_DIRS = (os.path.join(PROJECT_DIR, "templates"),
)

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'mboapi_djangodemo.wsgi.application'

LANGUAGE_CODE = 'en-us'
TIME_ZONE = 'UTC'
USE_I18N = True
USE_L10N = True
USE_TZ = True


DATABASES = {}

#different settings based on system name
if (socket.gethostname() != 'vacro' ) and (socket.gethostname() != 'joe-VirtualBox'):
    DATABASES['default'] =  dj_database_url.config()
    print(socket.gethostname())
    DEBUG = False
    STATIC_ROOT = 'staticfiles'
    STATIC_URL = '/static/'
    STATICFILES_DIRS = (os.path.join(BASE_DIR, '../mboapi_djangodemo/static'),)

else:
    LOCAL_PROJECT_DIR = os.path.abspath(os.path.dirname(__file__))
    DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(LOCAL_PROJECT_DIR, 'testingdb.db'),
        }
    }
    STATIC_ROOT = 'staticfiles'
    STATIC_URL = '/static/'
    STATICFILES_DIRS = (os.path.join(BASE_DIR, 'static'),)
        


SECURE_PROXY_SSL_HEADER = ('HTTP_X_FORWARDED_PROTO', 'https')
ALLOWED_HOSTS = ['*']

    
CRISPY_TEMPLATE_PACK = 'bootstrap3'

LOGIN_URL = '/web/login'
LOGOUT_URL = '/web/logout'
LOGIN_REDIRECT_URL = '/web/current'



